### Data Cleaning

##### Data Exploration

- Reading csv from the data folder

In [ ]:
import pandas as pd

In [ ]:
# For Reading data from csv file 
df = pd.read_csv('../data/raw/synthetic_customers.csv')

In [ ]:
# For checking 1st 5 rows of data
df.head()

,customer_id,age,gender,region,device,signup_date,last_purchase_date,purchase_count,preferred_category,loyalty_tier,avg_order_value,coupon_used_pct,payment_method,total_spent,recency_days,churned
0,1,23,Female,East,Mobile,2022-10-30,2022-10-31,0,Groceries,Bronze,34.77,0.263,PayPal,0.00,1157,1
1,2,66,Female,North,Mobile,2022-06-23,2024-02-17,4,Groceries,Silver,44.53,0.361,Debit Card,219.04,683,1
2,3,59,Male,North,Mobile,2023-02-27,2023-05-23,0,Clothing,Bronze,64.93,0.279,Credit Card,0.00,953,1
3,4,45,Male,West,Desktop,2023-11-29,2025-05-17,4,Home,Silver,45.49,0.088,Debit Card,181.26,228,0
4,5,45,Female,South,Mobile,2019-06-02,2019-06-14,0,Groceries,Bronze,43.67,0.369,Credit Card,0.00,2392,1

In [ ]:
# For checking 1st 5 rows of data
df.tail()

,customer_id,age,gender,region,device,signup_date,last_purchase_date,purchase_count,preferred_category,loyalty_tier,avg_order_value,coupon_used_pct,payment_method,total_spent,recency_days,churned
14995,14996,49,Female,Central,Desktop,2020-02-25,2021-08-26,3,Beauty,Silver,46.65,0.234,Debit Card,137.01,1588,1
14996,14997,52,Male,South,Mobile,2021-07-08,2023-03-07,5,Home,Bronze,72.22,0.112,PayPal,341.63,1030,1
14997,14998,59,Female,North,Desktop,2021-08-15,2022-01-16,1,Books,Silver,17.38,0.095,Credit Card,17.72,1445,1
14998,14999,47,Female,South,Mobile,2020-03-26,2021-12-31,10,Groceries,Silver,42.26,0.301,PayPal,276.52,1461,1
14999,15000,19,Male,Central,Mobile,2019-08-16,2019-09-06,0,Sports,Bronze,51.18,0.659,Credit Card,0.00,2308,0

In [ ]:
# to see the df rows count 
df.shape

(15000, 16)

In [ ]:
# To see the datatypes 
df.dtypes

customer_id             int64
age                     int64
gender                    str
region                    str
device                    str
signup_date               str
last_purchase_date        str
purchase_count          int64
preferred_category        str
loyalty_tier              str
avg_order_value       float64
coupon_used_pct       float64
payment_method            str
total_spent           float64
recency_days            int64
churned                 int64
dtype: object

In [ ]:
# To See the whole information 
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customer_id         15000 non-null  int64
 1   age                 15000 non-null  int64
 2   gender              15000 non-null  str
 3   region              15000 non-null  str
 4   device              15000 non-null  str
 5   signup_date         15000 non-null  str
 6   last_purchase_date  15000 non-null  str
 7   purchase_count      15000 non-null  int64
 8   preferred_category  15000 non-null  str
 9   loyalty_tier        15000 non-null  str
 10  avg_order_value     15000 non-null  float64
 11  coupon_used_pct     15000 non-null  float64
 12  payment_method      15000 non-null  str
 13  total_spent         15000 non-null  float64
 14  recency_days        15000 non-null  int64
 15  churned             15000 non-null  int64
dtypes: float64(3), int64(5), str(8)
memory usage: 1.8 MB

In [ ]:
# To get to know the statistics of df 
df.describe()

,customer_id,age,purchase_count,avg_order_value,coupon_used_pct,total_spent,recency_days,churned
count,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000
mean,7500.500000,48.780067,2.829600,60.183585,0.336185,170.581837,942.790067,0.712200
std,4330.271354,18.112838,2.417634,50.734020,0.160888,242.107731,716.448198,0.452752
min,1.000000,18.000000,0.000000,4.430000,0.005000,0.000000,0.000000,0.000000
25%,3750.750000,33.000000,1.000000,27.890000,0.213000,30.530000,265.000000,0.000000
50%,7500.500000,49.000000,2.000000,45.415000,0.321000,94.910000,910.000000,1.000000
75%,11250.250000,64.000000,4.000000,75.620000,0.445000,214.572500,1545.250000,1.000000
max,15000.000000,80.000000,14.000000,840.660000,0.910000,4177.490000,2552.000000,1.000000

In [ ]:
# To get to know the statistics of df (non numerical cols )
df.describe(include='object')

C:\Users\gorla\AppData\Local\Temp\ipykernel_16260\436763538.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include='object')

,gender,region,device,signup_date,last_purchase_date,preferred_category,loyalty_tier,payment_method
count,15000,15000,15000,15000,15000,15000,15000,15000
unique,3,5,3,2546,2424,7,4,5
top,Female,North,Mobile,2024-03-20,2025-12-31,Groceries,Bronze,Credit Card
freq,7498,3272,9723,16,2205,3353,8032,7159

##### Data Cleaning
- 1. Null Values 
- 2. Duplicates 
- 3. Outliers
- 4. Anamoly Detection (Data Inconsitency)
- 5. Interpolation

In [ ]:
# df.isnull() # 1 : Finding Null values (Operation)
# df[df.isnull()] # 2 : Get the above result in dataframe (To get the operation result in df df[operation])

,customer_id,age,gender,region,device,signup_date,last_purchase_date,purchase_count,preferred_category,loyalty_tier,avg_order_value,coupon_used_pct,payment_method,total_spent,recency_days,churned
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14997,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14998,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.isnull().sum()

customer_id           0
age                   0
gender                0
region                0
device                0
signup_date           0
last_purchase_date    0
purchase_count        0
preferred_category    0
loyalty_tier          0
avg_order_value       0
coupon_used_pct       0
payment_method        0
total_spent           0
recency_days          0
churned               0
dtype: int64

In [ ]:
# df.duplicated()
df[df.duplicated()]

Empty DataFrame
Columns: [customer_id, age, gender, region, device, signup_date, last_purchase_date, purchase_count, preferred_category, loyalty_tier, avg_order_value, coupon_used_pct, payment_method, total_spent, recency_days, churned]
Index: []

In [ ]:
df.drop_duplicates()

In [ ]:
df.describe()

,customer_id,age,purchase_count,avg_order_value,coupon_used_pct,total_spent,recency_days,churned
count,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000
mean,7500.500000,48.780067,2.829600,60.183585,0.336185,170.581837,942.790067,0.712200
std,4330.271354,18.112838,2.417634,50.734020,0.160888,242.107731,716.448198,0.452752
min,1.000000,18.000000,0.000000,4.430000,0.005000,0.000000,0.000000,0.000000
25%,3750.750000,33.000000,1.000000,27.890000,0.213000,30.530000,265.000000,0.000000
50%,7500.500000,49.000000,2.000000,45.415000,0.321000,94.910000,910.000000,1.000000
75%,11250.250000,64.000000,4.000000,75.620000,0.445000,214.572500,1545.250000,1.000000
max,15000.000000,80.000000,14.000000,840.660000,0.910000,4177.490000,2552.000000,1.000000

In [ ]:
import numpy as np 
Q3 = np.percentile(df['age'],0.75)
Q1 = np.percentile(df['age'],0.25)

IQR = Q3-Q1

lower_limit = IQR*1.5 + Q1
upper_limit = IQR*1.5 + Q3


Q1,Q3,IQR,lower_limit,upper_limit

In [ ]:
df['age'].unique()

In [ ]:
df['age'].value_counts()

In [ ]:
df['age'].percentile(0.75)

In [ ]:
age = 0

df[df['age'] == '19+E0'].drop()

In [ ]:
df.drop()

##### Operaters

- 1. Arthimeitc 
- 2. Logical 
- 3. Boolean
- 4. Comparision 
- 5. Membership
- 6. Aggregation

In [ ]:
df['age'] + 10

In [ ]:
df['BMI'] = df['age']*1.5 + df['weight']*0.69

In [ ]:
df[(df['age']> 10) and (df['gender'] == 'F')] # and 
df[(df['age']> 10) or (df['gender'] == 'F')] # or 
df[(df['age']> 10) not (df['gender'] == 'F')] # or 
df[~df['gender'] == 'M']

In [ ]:
df[~df['age'].isin([10,20,30])]

##### Common Functions

##### Joins