In [2]:
import pandas as pd
##import numpy as np

In [17]:
df=pd.read_csv(r'D:\customer_purchasing_pattern_analysis_using_AI\customer-purchasing-pattern-analysis-using-AI\data\raw\synthetic_customers.csv')
df.head()

,customer_id,age,gender,region,device,signup_date,last_purchase_date,purchase_count,preferred_category,loyalty_tier,avg_order_value,coupon_used_pct,payment_method,total_spent,recency_days,churned
0,1,23,Female,East,Mobile,2022-10-30,2022-10-31,0,Groceries,Bronze,34.77,0.263,PayPal,0.00,1157,1
1,2,66,Female,North,Mobile,2022-06-23,2024-02-17,4,Groceries,Silver,44.53,0.361,Debit Card,219.04,683,1
2,3,59,Male,North,Mobile,2023-02-27,2023-05-23,0,Clothing,Bronze,64.93,0.279,Credit Card,0.00,953,1
3,4,45,Male,West,Desktop,2023-11-29,2025-05-17,4,Home,Silver,45.49,0.088,Debit Card,181.26,228,0
4,5,45,Female,South,Mobile,2019-06-02,2019-06-14,0,Groceries,Bronze,43.67,0.369,Credit Card,0.00,2392,1

In [10]:
df.tail

<bound method NDFrame.tail of        customer_id  age  gender   region   device signup_date  \
0                1   23  Female     East   Mobile  2022-10-30
1                2   66  Female    North   Mobile  2022-06-23
2                3   59    Male    North   Mobile  2023-02-27
3                4   45    Male     West  Desktop  2023-11-29
4                5   45  Female    South   Mobile  2019-06-02
...            ...  ...     ...      ...      ...         ...
14995        14996   49  Female  Central  Desktop  2020-02-25
14996        14997   52    Male    South   Mobile  2021-07-08
14997        14998   59  Female    North  Desktop  2021-08-15
14998        14999   47  Female    South   Mobile  2020-03-26
14999        15000   19    Male  Central   Mobile  2019-08-16

      last_purchase_date  purchase_count preferred_category loyalty_tier  \
0             2022-10-31               0          Groceries       Bronze
1             2024-02-17               4          Groceries       Silver
2             2023-05-23               0           Clothing       Bronze
3             2025-05-17               4               Home       Silver
4             2019-06-14               0          Groceries       Bronze
...                  ...             ...                ...          ...
14995         2021-08-26               3             Beauty       Silver
14996         2023-03-07               5               Home       Bronze
14997         2022-01-16               1              Books       Silver
14998         2021-12-31              10          Groceries       Silver
14999         2019-09-06               0             Sports       Bronze

       avg_order_value  coupon_used_pct payment_method  total_spent  \
0                34.77            0.263         PayPal         0.00
1                44.53            0.361     Debit Card       219.04
2                64.93            0.279    Credit Card         0.00
3                45.49            0.088     Debit Card       181.26
4                43.67            0.369    Credit Card         0.00
...                ...              ...            ...          ...
14995            46.65            0.234     Debit Card       137.01
14996            72.22            0.112         PayPal       341.63
14997            17.38            0.095    Credit Card        17.72
14998            42.26            0.301         PayPal       276.52
14999            51.18            0.659    Credit Card         0.00

       recency_days  churned
0              1157        1
1               683        1
2               953        1
3               228        0
4              2392        1
...             ...      ...
14995          1588        1
14996          1030        1
14997          1445        1
14998          1461        1
14999          2308        0

[15000 rows x 16 columns]>

In [16]:
pd.read_csv('D:\customer_purchasing_pattern_analysis_using_AI\customer-purchasing-pattern-analysis-using-AI\data\\raw\synthetic_customers.csv')

<>:1: SyntaxWarning: "\c" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\c"? A raw string is also an option.
<>:1: SyntaxWarning: "\c" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\c"? A raw string is also an option.
C:\Users\gorla\AppData\Local\Temp\ipykernel_9816\688052022.py:1: SyntaxWarning: "\c" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\c"? A raw string is also an option.
  pd.read_csv('D:\customer_purchasing_pattern_analysis_using_AI\customer-purchasing-pattern-analysis-using-AI\data\\raw\synthetic_customers.csv')

,customer_id,age,gender,region,device,signup_date,last_purchase_date,purchase_count,preferred_category,loyalty_tier,avg_order_value,coupon_used_pct,payment_method,total_spent,recency_days,churned
0,1,23,Female,East,Mobile,2022-10-30,2022-10-31,0,Groceries,Bronze,34.77,0.263,PayPal,0.00,1157,1
1,2,66,Female,North,Mobile,2022-06-23,2024-02-17,4,Groceries,Silver,44.53,0.361,Debit Card,219.04,683,1
2,3,59,Male,North,Mobile,2023-02-27,2023-05-23,0,Clothing,Bronze,64.93,0.279,Credit Card,0.00,953,1
3,4,45,Male,West,Desktop,2023-11-29,2025-05-17,4,Home,Silver,45.49,0.088,Debit Card,181.26,228,0
4,5,45,Female,South,Mobile,2019-06-02,2019-06-14,0,Groceries,Bronze,43.67,0.369,Credit Card,0.00,2392,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,14996,49,Female,Central,Desktop,2020-02-25,2021-08-26,3,Beauty,Silver,46.65,0.234,Debit Card,137.01,1588,1
14996,14997,52,Male,South,Mobile,2021-07-08,2023-03-07,5,Home,Bronze,72.22,0.112,PayPal,341.63,1030,1
14997,14998,59,Female,North,Desktop,2021-08-15,2022-01-16,1,Books,Silver,17.38,0.095,Credit Card,17.72,1445,1
14998,14999,47,Female,South,Mobile,2020-03-26,2021-12-31,10,Groceries,Silver,42.26,0.301,PayPal,276.52,1461,1
14999,15000,19,Male,Central,Mobile,2019-08-16,2019-09-06,0,Sports,Bronze,51.18,0.659,Credit Card,0.00,2308,0